/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Career as PrismaCareer } from "@prisma/client";

export class CareerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CareerCountArgs, "select">): Promise<number> {
    return this.prisma.career.count(args);
  }

  async careers(args: Prisma.CareerFindManyArgs): Promise<PrismaCareer[]> {
    return this.prisma.career.findMany(args);
  }
  async career(
    args: Prisma.CareerFindUniqueArgs
  ): Promise<PrismaCareer | null> {
    return this.prisma.career.findUnique(args);
  }
  async createCareer(args: Prisma.CareerCreateArgs): Promise<PrismaCareer> {
    return this.prisma.career.create(args);
  }
  async updateCareer(args: Prisma.CareerUpdateArgs): Promise<PrismaCareer> {
    return this.prisma.career.update(args);
  }
  async deleteCareer(args: Prisma.CareerDeleteArgs): Promise<PrismaCareer> {
    return this.prisma.career.delete(args);
  }
}
