/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoadmapService } from "../roadmap.service";
import { RoadmapCreateInput } from "./RoadmapCreateInput";
import { Roadmap } from "./Roadmap";
import { RoadmapFindManyArgs } from "./RoadmapFindManyArgs";
import { RoadmapWhereUniqueInput } from "./RoadmapWhereUniqueInput";
import { RoadmapUpdateInput } from "./RoadmapUpdateInput";

export class RoadmapControllerBase {
  constructor(protected readonly service: RoadmapService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Roadmap })
  async createRoadmap(
    @common.Body() data: RoadmapCreateInput
  ): Promise<Roadmap> {
    return await this.service.createRoadmap({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Roadmap] })
  @ApiNestedQuery(RoadmapFindManyArgs)
  async roadmaps(@common.Req() request: Request): Promise<Roadmap[]> {
    const args = plainToClass(RoadmapFindManyArgs, request.query);
    return this.service.roadmaps({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Roadmap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async roadmap(
    @common.Param() params: RoadmapWhereUniqueInput
  ): Promise<Roadmap | null> {
    const result = await this.service.roadmap({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Roadmap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRoadmap(
    @common.Param() params: RoadmapWhereUniqueInput,
    @common.Body() data: RoadmapUpdateInput
  ): Promise<Roadmap | null> {
    try {
      return await this.service.updateRoadmap({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Roadmap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRoadmap(
    @common.Param() params: RoadmapWhereUniqueInput
  ): Promise<Roadmap | null> {
    try {
      return await this.service.deleteRoadmap({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
