/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AlternativeRoute } from "./AlternativeRoute";
import { AlternativeRouteCountArgs } from "./AlternativeRouteCountArgs";
import { AlternativeRouteFindManyArgs } from "./AlternativeRouteFindManyArgs";
import { AlternativeRouteFindUniqueArgs } from "./AlternativeRouteFindUniqueArgs";
import { DeleteAlternativeRouteArgs } from "./DeleteAlternativeRouteArgs";
import { AlternativeRouteService } from "../alternativeRoute.service";
@graphql.Resolver(() => AlternativeRoute)
export class AlternativeRouteResolverBase {
  constructor(protected readonly service: AlternativeRouteService) {}

  async _alternativeRoutesMeta(
    @graphql.Args() args: AlternativeRouteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AlternativeRoute])
  async alternativeRoutes(
    @graphql.Args() args: AlternativeRouteFindManyArgs
  ): Promise<AlternativeRoute[]> {
    return this.service.alternativeRoutes(args);
  }

  @graphql.Query(() => AlternativeRoute, { nullable: true })
  async alternativeRoute(
    @graphql.Args() args: AlternativeRouteFindUniqueArgs
  ): Promise<AlternativeRoute | null> {
    const result = await this.service.alternativeRoute(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AlternativeRoute)
  async deleteAlternativeRoute(
    @graphql.Args() args: DeleteAlternativeRouteArgs
  ): Promise<AlternativeRoute | null> {
    try {
      return await this.service.deleteAlternativeRoute(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
